// Generated by bench2verilog.py
module decoder_2x4(
    A0, A1, Y0, Y1, Y2, Y3
);

  input  A0, A1;
  output Y0, Y1, Y2, Y3;
  wire   CONST0, CONST1, n_not_A0, n_not_A1, p_Y0_0, p_Y1_0, p_Y2_0, p_Y3_0;

  assign CONST0 = (A0 & n_not_A0);
  assign CONST1 = (A0 | n_not_A0);
  assign Y0 = p_Y0_0;
  assign Y1 = p_Y1_0;
  assign Y2 = p_Y2_0;
  assign Y3 = p_Y3_0;
  assign n_not_A0 = ~(A0);
  assign n_not_A1 = ~(A1);
  assign p_Y0_0 = (n_not_A0 & n_not_A1);
  assign p_Y1_0 = (A0 & n_not_A1);
  assign p_Y2_0 = (n_not_A0 & A1);
  assign p_Y3_0 = (A0 & A1);

endmodule
